### PR TITLE
Add JSPM

### PR DESCRIPTION
**Pull request by adamburgess**
This patch adds [JSPM](https://github.com/jspm/jspm-cli), version 0.17 beta 5. This latest beta version utilises rollup.

I haven't measured the times.

one small note: JSPM expects modules to be in a subdirectory. I had to symlink the src directory to get around this.

### CODE REVIEW

**Comment by samccone** [comment]
boom awesome thanks for the PR!

I will land this tonight with all of the others... thanks!

**Comment by samccone** [comment]
Hi @AdamBurgess turns out this patch causes the code to be broken

screen shot 2016-02-02 at 6 03 14 pm

Let me know if you get this working

**Comment by adamburgess** [comment]
It seemed to work for me when I bundled it....I'll test again.

**Comment by samccone** [comment]
(going to investigate the src code changes needed to enable this kind of mangling so no action needed just yet)

**Comment by adamburgess** [comment]
It works for me fine in Chrome 50.0.2633.3...
Are you still getting a 14993 byte file?

## 

If you think it's due to mangling, you can add --no-mangle to `jspm build`, which brings the total size up to 19,943 bytes.

**Comment by samccone** [comment]
manually landed... thanks!

you can track the progress here
https://github.com/samccone/The-cost-of-transpiling-es2015-in-2016/tree/mangle

**Pull request closed without merging**
