### PR TITLE
Measure tool runtime in the compile scripts

### PR DESCRIPTION
**Pull request by paulirish**
Not sure how you were doing this before…

But these setup seems the most fair and balanced. wdyt?

### CODE REVIEW

**Comment by stevemao** [comment]
This is probably not the best practice of using `npm-scripts`. For long-term benefits you might wanna use an external build tool :)

**Comment by nstepien** [comment]
Maybe move that into the Makefile? `time npm run compile`

**Comment by paulirish** [comment]
@MayhemYDG Yahhhhhhh that's much better.

**Comment by paulirish** [comment]
moved into makefile.

**Comment by samccone** [comment]
yeah seems more balanced for sure.. I will regen these numbers

**Comment by samccone** [comment]
:bow: thx for the PR

**Pull request merged**
